development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: redis://redistogo:aa9f2b46bbfce3340c6f6d6f610d636d@scat.redistogo.com:10761/
#  channel_prefix: demo_production
